INDEX = (
    'All Races',
    'Orc',
    'Skaven',
    'Dark Elves',
    'Humans',
    'Dwarves',
    'High Elves',
    'Goblins',
    'Halflings',
    'Chaos Dwarves',
    'Chaos',
    'Undead',
    'Wood Elves',
    'Norse',
    'Amazons',
    'Lizardmen',
    'Nurgle\'s Rotters',
    'Khemri',
    'Necromantic',
    'Elves',
    'Ogres',
    'Vampires',
    'Slann',
    'Underworld',
    'Chaos Pact',
    'Khorne',
    'Bretonnians',
    'Multiple Races')
